DataScience_HW3
================
2024-10-10

## Problem 1

Size of dataset before data cleaning: 7 variables (columns) and 2595176
observations (rows).

Variable names include: id, date, prcp, snow, snwd, tmax, tmin.

There is a significant amount of missing data

``` r
filter(ny_noaa, (is.na(snow) | snow == "") &
         (is.na(tmin) | tmin == "") &
         (is.na(tmax) | tmax == "") &
         (is.na(prcp) | prcp == "")) %>% 
  nrow()
```

    ## [1] 73950

There are 73950 rows that have missing data in all four columns tmax,
tmin, prcp, and snow.

``` r
filter(ny_noaa, (is.na(tmin) | tmin == "") &
         (is.na(tmax) | tmax == "")) %>% 
  nrow()
```

    ## [1] 1132502

And 1132502 rows that have missing data for both coloumns tmax and tmin.

The missing data is an issue, as there is inconsistancy in the data /
information.

**Do some data cleaning. Create separate variables for year, month, and
day.**

``` r
dated_ny_noaa = 
  ny_noaa %>% 
  mutate(
    year = year(date),
    month = month(date),
    day = day(date)
  ) %>% 
  select(-date)
```

**Ensure observations for temperature, precipitation, and snowfall are
given in reasonable units.**

Current units –\>

- temperature in 10ths of degrees celcius (need to be converted to whole
  degrees celcius)

- precipitation in tenths of mm (to be converted to mm)

- snowfall in mm (can remain in mm or converted to cm)

``` r
dated_ny_noaa = 
  dated_ny_noaa %>% 
  mutate(tmax = as.integer(tmax), 
         tmin = as.integer(tmin)) %>% 
  mutate(tmax = tmax / 10, 
         tmin = tmin / 10, 
         prcp = prcp / 10)
```

**For snowfall, what are the most commonly observed values? Why?**

``` r
dated_ny_noaa %>% 
  filter(snow > 0) %>%
  group_by(snow) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count)) %>%
  slice_head(n = 5) %>%
  pull(snow)              
```

    ## [1] 25 13 51 76  8

Most commonly observed value was 0 snowfall, followed by 25, 13, 51 and
76mm of snow fall.

This is consistent with the fact that it only snows in the coldest
months of winter in NY therefore majority of the observations will have
0 snow. It is also noted that on average, NYC sees around 29.8 inches of
snow in a season which is relatively consistent with the most commonly
observed values of snowfall in this data frame.

**Make a two-panel plot showing the average max temperature in January
and in July in each station across years. Is there any observable /
interpretable structure? Any outliers?**

``` r
avg_tmax_1 = 
dated_ny_noaa %>% 
  filter(month == 1) %>% 
  group_by(id, year, month) %>% 
  summarise(mean_value = mean(tmax, na.rm = TRUE)) %>% 
  filter(!is.na(mean_value))
```

    ## `summarise()` has grouped output by 'id', 'year'. You can override using the
    ## `.groups` argument.

``` r
avg_tmax_7 = 
dated_ny_noaa %>% 
  filter(month == 7) %>% 
  group_by(id, year, month) %>% 
  summarise(mean_value = mean(tmax, na.rm = TRUE)) %>% 
  filter(!is.na(mean_value))
```

    ## `summarise()` has grouped output by 'id', 'year'. You can override using the
    ## `.groups` argument.

``` r
tmax_1_p = 
  avg_tmax_1 %>% 
  ggplot(aes(x = year, y = mean_value, color = id)) +
  geom_point(alpha = .5) +
  labs(title = "Average Maximum Temperature of Stations in January across Years and Stations",
       x = "Year",  
       y = "Average Maximum Temperature (°C)") + 
  theme(legend.position = "none")

tmax_7_p = 
  avg_tmax_7 %>% 
  ggplot(aes(x = year, y = mean_value, color = id)) +
  geom_point(alpha = .5) +
  labs(title = "Average Maximum Temperature of Stations in July across Years and Stations",
       x = "Year",  
       y = "Average Maximum Temperature (°C)") + 
  theme(legend.position = "none")

tmax_1_p + tmax_7_p
```

![](p8105_fp2513_hw3_files/figure-gfm/unnamed-chunk-6-1.png)<!-- -->

In general the average maximum temperatures in January are more varied
across the years and spread out within the year then those in July.

There may be a slight upward trend of the average maximum temperature in
January as the years pass, but this is only very slight and would need
to be further confirmed.

Some noticeable outliers include in the year 1981 January where there
was an extremely low temperature recording average of about -17 degrees
Celsius. Where the other stations recorded around the 2 to -7 degrees
Celsius range. Similarly in January 2005, one station recorded a low of
-14 degree Celsius where the other stations in that same time averaged
around 5 to -5 degrees Celsius.

One outlier of Average Maximum Temperature in July is 1988 where one
station averaged below 15 degrees Celsius, where other stations in that
month had average recordings around 25 to 30 degrees Celsius.

**Make a two-panel plot showing (i) tmax vs tmin for the full dataset
(note that a scatterplot may not be the best option);**

**(ii) make a plot showing the distribution of snowfall values greater
than 0 and less than 100 separately by year.**

## Problem 2

**Load, tidy, merge, and otherwise organize the data sets. Your final
dataset should include all originally observed variables; exclude
participants less than 21 years of age, and those with missing
demographic data; and encode data with reasonable variable classes
(i.e. not numeric, and using factors with the ordering of tables and
plots in mind).**

``` r
demographic_df = 
  read_csv(file = "data/nhanes_covar.csv", 
           na = c("NA", ",", ".")) %>% 
  janitor::clean_names()
```

    ## New names:
    ## Rows: 254 Columns: 5
    ## ── Column specification
    ## ──────────────────────────────────────────────────────── Delimiter: "," chr
    ## (5): ...1, 1 = male, ...3, ...4, 1 = Less than high school
    ## ℹ Use `spec()` to retrieve the full column specification for this data. ℹ
    ## Specify the column types or set `show_col_types = FALSE` to quiet this message.
    ## • `` -> `...1`
    ## • `` -> `...3`
    ## • `` -> `...4`

``` r
accelerometer_df = 
  read_csv(file = "data/nhanes_accel.csv", 
           na = c("NA", ",", ".")) %>% 
  janitor::clean_names()
```

    ## Rows: 250 Columns: 1441
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (1441): SEQN, min1, min2, min3, min4, min5, min6, min7, min8, min9, min1...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
demographic_df = 
  demographic_df %>% 
  { 
    colnames(.) <- as.character(.[4, ])
    .[-4, ]
  } %>% 
  slice(-1,-2,-3) %>% 
  mutate(
    age = as.numeric(age),
    BMI = as.numeric(BMI),
    sex = 
      case_match(
        sex, 
        "1" ~ "male", 
        "2" ~ "female"),
    sex = as.factor(sex),
    education = 
      case_match(
        education, 
        "1" ~ "less_than_high_school",
        "2" ~ "high_school_equivalent",
        "3" ~ "more_than_high_school"), 
    education = as.factor(education)
  ) %>% 
  filter(age > 20) %>% 
  drop_na() %>% 
  rename(seqn = SEQN)
```

``` r
accelerometer_df =
  accelerometer_df %>%
  pivot_longer(
    cols = starts_with("min"),
    names_to = "minute", 
    names_prefix = "min",
    values_to = "MIMS_values" 
  ) %>% 
  mutate(
    seqn = as.character(seqn)
  )
```

``` r
Demo_Acc_Join_df =
  left_join(demographic_df, accelerometer_df, by = "seqn")
```

**Produce a reader-friendly table for the number of men and women in
each education category, and create a visualization of the age
distributions for men and women in each education category. Comment on
these items.**

``` r
Sex_Edu_df =
  Demo_Acc_Join_df %>% 
  group_by(education, sex) %>%
  summarise(count = n(), .groups = 'drop') %>%
  pivot_wider(
    names_from = sex, 
    values_from = count)
  
kable(Sex_Edu_df, caption = "Number of Participants by Education and Sex")
```

| education              | female |  male |
|:-----------------------|-------:|------:|
| high_school_equivalent |  33120 | 50400 |
| less_than_high_school  |  40320 | 38880 |
| more_than_high_school  |  84960 | 80640 |

Number of Participants by Education and Sex

``` r
Sex_Edu_df %>% 
  pivot_longer(
    cols = female:male, 
    names_to = "sex", 
    values_to = "count") %>% 
  mutate(
    education = factor(education, levels = c("less_than_high_school", "high_school_equivalent", "more_than_high_school"))
  ) %>% 
  ggplot(aes(x = education, y = count, fill = sex)) + 
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Number of participants by Education level and Sex",
       x = "Education",
       y = "Number of participants",
       fill = "Sex") +
  theme_minimal()
```

![](p8105_fp2513_hw3_files/figure-gfm/unnamed-chunk-13-1.png)<!-- -->

``` r
Demo_Acc_Join_df %>% 
  group_by(education, sex) %>% 
  mutate(
    education = factor(education, levels = c("less_than_high_school", "high_school_equivalent", "more_than_high_school"))
  ) %>% 
  ggplot(aes(x = education, y = age, fill = sex)) +
  geom_boxplot()
```

![](p8105_fp2513_hw3_files/figure-gfm/unnamed-chunk-14-1.png)<!-- -->

In general there are a significantly greater number of participants in
this study that have a ‘more than high school’ education level (~ 80000
for both females and males, whereas the other two education levels hover
around the 40000 mark). The number of females and males are relatively
similar for those categorised in ‘more tan high school’ and ‘less than
high school’ education level. There are however more males (~ 50000)
than females (~ 35000) which are high school students in this study.
Overall, there are more males than females in this study.

In the ‘more than high school’ and ‘less than high school’ education
levels the age distribution for the males and females are similar within
their respective education levels. They share similar ranges, similar
interquartile ranges and medians. In the ‘high school equivalent’
education level the females have a older age distribution, with a high
median around 60, compared to the males at 50. While the interquartile
ranges still overlap, the females are pulled older from ~45 to ~75 years
old, where the males interquartile range covers ~30 to ~65 years old.

Those males and females of the ‘more than high school’ education level
have a younger age distribution (indicated by the median around 40 years
old) than those from a ‘less than high school’ (60) or ‘high school
equivalent’ (~55-60) education level.

**Traditional analyses of accelerometer data focus on the total activity
over the day. Using your tidied dataset, aggregate across minutes to
create a total activity variable for each participant. Plot these total
activities (y-axis) against age (x-axis); your plot should compare men
to women and have separate panels for each education level. Include a
trend line or a smooth to illustrate differences. Comment on your
plot.**

``` r
Daily_act_df = 
  Demo_Acc_Join_df %>% 
  group_by(seqn) %>% 
  mutate(
    daily_activity = 
      sum(MIMS_values, na.rm = TRUE)) %>% 
  ungroup()
```

``` r
daily_act_edu_sex_p = 
  Daily_act_df %>% 
  mutate(
    education = factor(education, levels = c("less_than_high_school", "high_school_equivalent", "more_than_high_school"))
  ) %>% 
  ggplot(aes(x = age, y = daily_activity, color = sex)) + 
  geom_point(alpha = .5) + 
  geom_smooth(aes(group = sex), se = FALSE) + 
  facet_grid(. ~ education) + 
  theme_minimal()

print(daily_act_edu_sex_p)
```

    ## `geom_smooth()` using method = 'gam' and formula = 'y ~ s(x, bs = "cs")'

![](p8105_fp2513_hw3_files/figure-gfm/unnamed-chunk-16-1.png)<!-- -->

There seems to be a general downward trend where as the participant gets
older their total daily activity decreases too.

Those participants in the ‘more than high school’ education level have
the most consistent total daily activity across the ages. Whereas those
in the ‘less than high school’ education level show an obvious decrease
in daily activity from 20 to 80 years olds.

There is an interesting pattern for all three education levels, where
around the 60 year old mark there are either prominent peaks or dips in
daily total activity that does not follow the general trend. For
instance in the ‘high school equivalent’ education level, around 60
years of both males and females participants have a sharp dip in total
daily activity. But in the ‘less than high school’ education level group
at around 60 years the females show a sudden drop and the males a peak
in total daily activity. This is the opposite for participants in the
‘more than high school’ education, males dipping and females peaking at
around 60 years.

**Accelerometer data allows the inspection activity over the course of
the day. Make a three-panel plot that shows the 24-hour activity time
courses for each education level and use color to indicate sex. Describe
in words any patterns or conclusions you can make based on this graph;
including smooth trends may help identify differences.**

This just doesn’t identify seperate individuals, this is just
